import React from 'react';
import {
    Activity,
    AlertCircle,
    BarChart3,
    BadgeCheck,
    Bell,
    Building2,
    Calendar,
    CalendarDays,
    CheckCircle,
    ChevronLeft,
    ChevronRight,
    Clock,
    Copy,
    CreditCard,
    Download,
    Eye,
    FilePen,
    FileText,
    Filter,
    Gavel,
    Globe,
    GripVertical,
    History,
    Info,
    Key,
    LayoutDashboard,
    Lock,
    LogOut,
    Mail,
    MapPin,
    Menu,
    Minus,
    MoreVertical,
    Phone,
    PieChart,
    Plus,
    Printer,
    RefreshCw,
    Search,
    Settings,
    Share2,
    Shield,
    SlidersHorizontal,
    Smartphone,
    Store,
    Router,
    Trash2,
    TriangleAlert,
    TrendingUp,
    TrendingDown,
    Trophy,
    Upload,
    User,
    UserPlus,
    Users,
    Wrench,
    X,
    ZoomIn,
    ZoomOut,
} from 'lucide-react';

const icons = {
    activity: Activity,
    add: Plus,
    alertCircle: AlertCircle,
    analytics: BarChart3,
    badgeCheck: BadgeCheck,
    bell: Bell,
    branches: Building2,
    calendar: Calendar,
    checkCircle: CheckCircle,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    clock: Clock,
    copy: Copy,
    corrections: FilePen,
    dashboard: LayoutDashboard,
    download: Download,
    edit_note: FilePen,
    event: CalendarDays,
    eye: Eye,
    fileText: FileText,
    filter: Filter,
    gavel: Gavel,
    globe: Globe,
    gripVertical: GripVertical,
    history: History,
    info: Info,
    key: Key,
    lock: Lock,
    logout: LogOut,
    mail: Mail,
    mapPin: MapPin,
    menu: Menu,
    minus: Minus,
    more: MoreVertical,
    payments: CreditCard,
    phone: Phone,
    pieChart: PieChart,
    plus: Plus,
    printer: Printer,
    refreshCw: RefreshCw,
    router: Router,
    schedule: Clock,
    search: Search,
    settings: Settings,
    share2: Share2,
    shield: Shield,
    slidersHorizontal: SlidersHorizontal,
    smartphone: Smartphone,
    store: Store,
    trash2: Trash2,
    triangleAlert: TriangleAlert,
    trendingUp: TrendingUp,
    trendingDown: TrendingDown,
    trophy: Trophy,
    upload: Upload,
    user: User,
    userPlus: UserPlus,
    work_history: Clock,
    users: Users,
    wrench: Wrench,
    x: X,
    zoomIn: ZoomIn,
    zoomOut: ZoomOut,
};

export function Icon({ name, className }) {
    const Cmp = icons[name];

    if (!Cmp) {
        return null;
    }

    return <Cmp className={className} aria-hidden="true" />;
}
