import React from 'react';
import { Icon } from '../../../shared/Icon.jsx';

function formatDateTime(value) {
    if (!value) return '—';
    try {
        return new Date(value).toLocaleString();
    } catch {
        return String(value);
    }
}

export function ReportHistory({ history, status, onRefresh, onDelete, onDownload }) {
    return (
        <div className="bg-white rounded-lg shadow-soft border border-slate-200 overflow-hidden">
            <div className="flex items-center justify-between p-6 border-b border-slate-200">
                <h3 className="text-lg font-bold text-slate-800">Generated Report History</h3>
                <button
                    type="button"
                    onClick={onRefresh}
                    className="flex items-center gap-2 text-sm text-[#0a1f43] font-semibold hover:text-[#0a1f43]/80 transition-colors"
                >
                    <Icon name="refreshCcw" className="h-4 w-4" />
                    Refresh
                </button>
            </div>
            <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                    <thead>
                        <tr className="bg-slate-50 border-b border-slate-200 text-xs uppercase tracking-wider text-slate-500 font-semibold">
                            <th className="px-6 py-4">Report Name</th>
                            <th className="px-6 py-4">Date Generated</th>
                            <th className="px-6 py-4">Generated By</th>
                            <th className="px-6 py-4">Format</th>
                            <th className="px-6 py-4 text-right">Action</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-200 text-sm">
                        {status === 'loading' ? (
                            <tr>
                                <td colSpan={5} className="px-6 py-8 text-center text-slate-500">
                                    Loading history...
                                </td>
                            </tr>
                        ) : status === 'error' ? (
                            <tr>
                                <td colSpan={5} className="px-6 py-8 text-center text-red-600 font-medium">
                                </td>
                            </tr>
                        ) : history.length === 0 ? (
                            <tr>
                                <td colSpan={5} className="px-6 py-8 text-center text-slate-500">
                                    No reports generated yet.
                                </td>
                            </tr>
                        ) : (
                            history.map((r) => (
                                <tr key={r.id} className="hover:bg-slate-50 transition-colors">
                                    <td className="px-6 py-4 font-semibold text-slate-800">{r.name}</td>
                                    <td className="px-6 py-4 text-slate-600 whitespace-nowrap">{formatDateTime(r.created_at)}</td>
                                    <td className="px-6 py-4 text-slate-600 whitespace-nowrap">{r.created_by_name || '—'}</td>
                                    <td className="px-6 py-4">
                                        <span
                                            className={`px-2 py-0.5 text-xs rounded font-bold ${String(r.format).toLowerCase() === 'csv'
                                                ? 'bg-blue-100 text-blue-800 border border-blue-200'
                                                : String(r.format).toLowerCase() === 'xlsx'
                                                    ? 'bg-amber-100 text-amber-800 border border-amber-200'
                                                    : 'bg-green-100 text-green-800 border border-green-200'
                                                }`}
                                        >
                                            {String(r.format ?? 'json').toUpperCase()}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4 text-right whitespace-nowrap">
                                        <div className="flex justify-end gap-1">
                                            <button
                                                type="button"
                                                onClick={() => onDelete(r.id, r.name)}
                                                className="p-1.5 text-slate-400 hover:text-red-600 hover:bg-red-50 rounded transition-colors"
                                                title="Delete"
                                            >
                                                <Icon name="trash2" className="h-5 w-5" />
                                            </button>
                                            <button
                                                type="button"
                                                onClick={() => onDownload(r.id, r.format, r.name)}
                                                className="p-1.5 text-slate-400 hover:text-[#0a1f43] hover:bg-slate-100 rounded transition-colors"
                                                title="Download"
                                            >
                                                <Icon name="download" className="h-5 w-5" />
                                            </button>
                                        </div>
                                    </td>
                                </tr>
                            ))
                        )}
                    </tbody>
                </table>
            </div>
        </div>
    );
}
